project:
  type: website
  output-dir: docs

website:
  title: "SPO-14582 Data Analysis"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Slides
        href: slides/index.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

